root = "." 
tmp_dir = "tmp" 

[build]   
  bin = "main" # The name of the binary file to be generated after building the project
  cmd = "go build -o {{.Output}} {{.Input}}" # The command to build the project
  exclude = ["tmp/*", "client/*"]  
  include = ["**/*.go"] 
  ignore = ["tmp/*"] 
